services:
  web:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    env_file:
      - .env/${ENVIRONMENT:-development}/database
      - .env/${ENVIRONMENT:-development}/web
    depends_on:
      - redis
      - database

  database:
    image: postgres:14.1
    env_file:
      - .env/${ENVIRONMENT:-development}/database
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis

volumes:
  data:
  gem_cache:
