version: '3'

services:
  web:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    env_file:
      - .env/${ENVIRONMENT:-development}/database
      - .env/${ENVIRONMENT:-development}/web
    depends_on:
      - redis
      - database

  database:
    image: postgres
    env_file:
      - .env/${ENVIRONMENT:-development}/database
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis



volumes:
  db_data:
  gem_cache:
